In [1]:
import numpy as n
import pandas as p
import matplotlib.pyplot as mp

In [3]:
n.__version__

'2.0.2'

In [4]:
a=n.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a.dtype

dtype('int64')

In [7]:
a[0]

np.int64(1)

In [8]:
a[5]

np.int64(6)

In [10]:
a=n.array(a,dtype=n.float64)
a

array([1., 2., 3., 4., 5., 6.])

In [11]:
a[0:3]

array([1., 2., 3.])

In [12]:
a[1:3]

array([2., 3.])

In [13]:
print(len(a))

6


In [15]:
print(a.shape)

(6,)


In [16]:
print(a.ndim)

1


In [19]:
a=n.array([[1,2],[3,5],[6,7],[8,9]])
print(len(a))
print(a.shape)
print(a.ndim)

4
(4, 2)
2


In [29]:
b=n.array([1,2,3,4,5])
b=n.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a = n.arange(1, 10).reshape(3, 3)
b = n.arange(10, 19).reshape(3, 3)

In [36]:
c=n.concatenate([a,b.T],axis=0)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [37]:
a[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
print(n.diag(b))
b

[10 14 18]


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [41]:
print(n.diag(n.fliplr(b)))

[12 14 16]


In [42]:
print(n.mean(b))

14.0


In [44]:
print(n.median(b))

14.0


In [46]:
print(n.min(a))

1


In [51]:
print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 13 16]
 [11 14 17]
 [12 15 18]]


In [52]:
a, b, c 

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 13, 16],
        [11, 14, 17],
        [12, 15, 18]]))

In [53]:
print(n.min(a))

1


In [56]:
print(n.max(a))

9


In [58]:
print(n.argmin(b))
b

0


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [59]:
print(n.argmax(b))

8


In [60]:
print(n.sort(b))

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [63]:
print(n.sort(b)[::-1])

[[16 17 18]
 [13 14 15]
 [10 11 12]]


In [65]:
print(n.std(b))

2.581988897471611


In [67]:
print(n.var(a))

6.666666666666667


In [69]:
d=n.array(['RISHABH JAIN'])
d

array(['RISHABH JAIN'], dtype='<U12')

In [71]:
d.dtype

dtype('<U12')

In [72]:
e=a+b
e

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [73]:
e+30

array([[41, 43, 45],
       [47, 49, 51],
       [53, 55, 57]])

In [83]:
a=n.array([1,2,3,4,5,6])
a
a=n.linspace(0,10,6)
a

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [85]:
a=p.Series([3,4,5,6,7])
a

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [87]:
a.index

RangeIndex(start=0, stop=5, step=1)