In [2]:
import numpy as np

In [4]:
#print version of the libary
np.__version__

'2.2.1'

In [7]:
#Methord 1 arry of float values
arr=np.array([1.0,2.2,3.5,4.1,5.7])
arr

array([1. , 2.2, 3.5, 4.1, 5.7])

In [8]:
arr.dtype

dtype('float64')

In [10]:
#Methord 1 arry of integers
arr=np.array([1,2,3,4,5])

In [11]:
#access arry element
arr[0]

np.int64(1)

In [12]:
#datatype of array
arr.dtype

dtype('int64')

In [13]:
#convert int array into float
arr=np.array(arr,dtype=np.float64)
arr

array([1., 2., 3., 4., 5.])

In [14]:
#slicing
arr[0:3]

array([1., 2., 3.])

In [16]:
#array of objects
arr=np.array(['juet','guna','M.P'])
arr

array(['juet', 'guna', 'M.P'], dtype='<U4')

In [17]:
arr=np.array([1,2,3,4,5])
#length of the array
print(len(arr))
#shape of array
print(arr.shape)
#dimentions of array
print(arr.ndim)

5
(5,)
1


In [18]:
#create 2D arry of matrix
arr=np.array([[1,2,3],[4,5,6]])
print('array contents \n',arr)
print('length=',len(arr))
#shape of thwe array
print('shape=',arr.shape)
#dimentions of the array
print('dimention=',arr.ndim)

array contents 
 [[1 2 3]
 [4 5 6]]
length= 2
shape= (2, 3)
dimention= 2
