In [5]:
import numpy as np

In [13]:
arr=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print(arr)
print('length=',len(arr))
print('shape=',arr.shape)
print('dimention=',arr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
length= 3
shape= (3, 3, 2)
dimention= 3


In [19]:
arr=np.array([[1,2],[3,4],[5,6]])
print(arr)
print('length=',len(arr))
print('shape=',arr.shape)
print('demention=',arr.ndim)

[[1 2]
 [3 4]
 [5 6]]
length= 3
shape= (3, 2)
demention= 2


In [23]:
arr=np.array([1,2])
print(arr)
print('length=',len(arr))
print('shape=',arr.shape)
print('dimention=',arr.ndim)

[1 2]
length= 2
shape= (2,)
dimention= 1
