In [1]:
import numpy as n

In [2]:
# using reshape function
a= n.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
b=n.arange(10,13).reshape(1,3)
b

array([[10, 11, 12]])

In [4]:
# concatenate of 2 arr
# 1 base on coloum which is axis 0, it means the concatenation will increase the vertical depth of the result arr
# the default axis 0 only
c=n.concatenate([a,b],axis=0)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
# concatenate of 2 arr
# 1 base on coloum which is axis 1, it means the concatenation witl increase the horizontal depth of the result arr
c=n.concatenate([a,b],axis=1)
c

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [6]:
# as a sol. we need to transpose the b from now matrix to coloum matrix i.e from shape(1,3) ro (3,1)
# built-in function to transpose if. T use it as b.T
c=n.concatenate([a,b.T],axis=1)
c

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [7]:
## acccessing arr element by 2 identical separated by [] or ,
# 1 separated by [] i.e [1. index for selection 1D arr] [2. index applied on arr selection by 1.]
a[:][:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# : means first [] is not filtering any thing so the second [] will select 0th row from a[:] selection
a[:][0]

array([1, 2, 3])

In [8]:
a[1:][0]

array([4, 5, 6])

In [9]:
## now when we use both indices work togather
a[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# first index will select all row starting from 1 & 2 index will select all colums starting from 2
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [11]:
print(a[:,0])
print(a[:,1])
print(a[:,2])

[1 4 7]
[2 5 8]
[3 6 9]


In [12]:
# orignal arr
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# modify the last row of the arr to be 10 10 10 
a[2,:]=10
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 10, 10]])

In [14]:
# modify the last column of the arr to be 7 7 7
a[:,2]=7
a

array([[ 1,  2,  7],
       [ 4,  5,  7],
       [10, 10,  7]])

In [15]:
# create a 2D arr of shape (3.3) using arange funtion of values starting from 11 to 19
d=n.arange(10,19).reshape(3,3)
d

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [20]:
print(n.diag(d))

[10 14 18]


In [21]:
print(n.diag(n.fliplr(d)))

[12 14 16]


In [25]:
e=[d[0,0],d[0,2],d[2,0],d[2,2]]
e

[np.int64(10), np.int64(12), np.int64(16), np.int64(18)]