In [1]:
import numpy as n

In [4]:
marks=n.array([23,34,45,56,67,78,89])
bonus=n.array([1,2,3,4,5,6,7])
final_marks=marks+bonus
final_marks

array([24, 36, 48, 60, 72, 84, 96])

In [5]:
a=n.array([1,2,3])
b=n.array([7])
c=a*b #broadcast*operation
c

array([ 7, 14, 21])

In [7]:
a=n.array([4,5,6])
b=a+10 #broadcast + operation
print(b)
c=a*10 #broadcast * operation
print(c)

[14 15 16]
[40 50 60]


In [9]:
a=n.linspace(0,10)
print(a)
print('length of a',len(a))
## no. of values =3
b=n.linspace(0,10,3)
print(b)
print('length of b',len(b))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
length of a 50
[ 0.  5. 10.]
length of b 3
